apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv0
spec:
  storageClassName: pv-mysql
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/srv/nfs/kubedata/pv0"
    server: 172.16.6.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
spec:
  storageClassName: pv-mysql
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/srv/nfs/kubedata/pv1"
    server: 172.16.6.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
spec:
  storageClassName: pv-mysql
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/srv/nfs/kubedata/pv3"
    server: 172.16.6.101
---
