apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-0
spec:
  storageClassName: pv-mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-1
spec:
  storageClassName: pv-mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-2
spec:
  storageClassName: pv-mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
